title: SpecIF
description: Home, Documentation and Tutorials of the Specification Integration Facility (SpecIF).
theme: just-the-docs

url: https://specif.de
heading_anchors: true

aux_links:
  Repo: https://github.com/GfSE/SpecIF-Pages
